---
apiVersion: v1
kind: Namespace
metadata:
  name: first-app
  labels:
    app: snake
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake
  namespace: snake
  labels:
    app: snake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      containers:
      - name: snake
        image: aschil/snake
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
    name: snake-service
    namespace: snake
spec:
    selector:
      app: snake
    ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake-ingress
  namespace: snake
  labels:
    app: snake
   annotations:
      haproxy.org/path-rewrite: "/"
      kubernetes.io/ingress.class: haproxy
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: host-service
            port:
              number: 9090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: snake
data:
