- name: get ingress_controller_port
  script: getPort.py "{{ ingress_controller_info_path }}"
  args:
    executable: python3
  register: ingress_controller_port

- debug:
    var: ingress_controller_port

- name: check ingress controller port
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    port: "{{ ingress_controller_port.stdout | int }}"
    timeout: 5
  register: ingress_controller_port_check
  ignore_errors: yes

- name: deploy terraform
  delegate_to: localhost
  terraform:
    project_path: "{{playbook_dir  }}/../terraform/"
    targets:
      - azurerm_network_security_group.master
    lock: no
    variables:
      ingress_controller_port: "{{ ingress_controller_port.stdout | int }}"
  when: ingress_controller_port_check is failed