- name: get ingress_controller_port
  script: getPort.py "{{ ingress_controller_info_path }}"
  register: ingress_controller_port

- name: check ingress controller port
  delegate_to: localhost
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    port: "{{ ingress_controller_port }}"
    timeout: 5
  register: ingress_controller_port_check
  ignore_errors: yes

- name: deploy terraform
  delegate_to: localhost
  terraform:
    project_path: "{{playbook_dir  }}/../terraform/" 
    variables:
      ingress_controller_port: "{{ ingress_controller_port }}"
  when: ingress_controller_port_check is failed