---
- name: enable firewall k8s-admin ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250-10252/tcp
    - 10255/tcp

- name: enable firewall k8s-worker ports
  firewalld:
    rich_rule: rule family=ipv4 source address="{{ hostvars[item].ansible_default_ipv4.address }}"/32 accept
    permanent: yes
    state: enabled
    immediate: yes
  with_items: 
    - "{{ groups['workers'] }}"