---
- name: enable firewall for nfs
  firewalld:
    service: nfs
    permanent: yes
    state: enabled
  notify: reload firewall

- name: enable firewall for rpc-bind
  firewalld:
    service: rpc-bind
    permanent: yes
    state: enabled
  notify: reload firewall

- name: enable firewall for mountd
  firewalld:
    service: mountd
    permanent: yes
    state: enabled
  notify: reload firewall