---
- name: setup machines
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - vmsetup

- name: nfs deploy
  hosts: nfss
  become: yes
  gather_facts: no
  roles:
    - nfsdeploy

- name: k8s install
  hosts: masters, workers
  become: yes
  gather_facts: no
  roles:
    - k8sinstall

- name: k8s masters
  hosts: masters
  become: yes
  gather_facts: no
  roles:
    - k8smasters

- name: k8s workers
  hosts: workers
  become: yes
  gather_facts: no
  roles:
    - k8sworkers

- name: application
  hosts: masters
  gather_facts: no
  roles:
    - application
