---
- name: check joined
  stat:
    path: /etc/kubernetes/pki/ca.crt
  register: joined_check

- name: join
  script: "{{ join_tmp_path }}"
  when: not joined_check.stat.exists
  notify:
    - reboot